import React from 'react';
import forest1 from '../../assets/images/example/forest-1.jpg'
import mountains1 from '../../assets/images/example/mountains-1.jpg'
import globalStyle from "../../assets/styles/globalStyle.module.scss";

function ContentPage() {
    return( 
        <div>
            <h1>Example Content Page</h1>
            <h2>Lorem ipsum</h2>
            <p className={globalStyle.textContent}>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vulputate fringilla lorem eu consectetur. Donec in finibus turpis, a aliquam est. Curabitur laoreet dignissim massa nec molestie. Praesent magna arcu, sagittis congue volutpat in, vestibulum nec mi. Cras hendrerit elementum felis, ac tristique dui pharetra ut. Etiam vel purus quis ex tincidunt tincidunt ac facilisis eros. Ut sed dictum velit, molestie efficitur magna. Suspendisse ut diam massa.</p>
            <p className={globalStyle.textContent}>Morbi tincidunt molestie nulla et placerat. In volutpat sollicitudin ipsum vitae faucibus. Proin consequat purus quis tellus pellentesque egestas. Cras eget aliquam lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam rhoncus ipsum arcu, at efficitur enim efficitur et. Mauris commodo sapien vitae ex tincidunt elementum. Aliquam dictum arcu vitae malesuada fringilla. Suspendisse in leo nulla. Donec lorem odio, dapibus at fermentum non, tempor ac ligula. Duis elementum quis sapien quis semper. Vivamus feugiat augue massa, eu mattis enim condimentum sed. Nullam bibendum viverra tempus. Praesent consequat consectetur enim, ac congue purus vehicula eget. Nulla ante eros, lobortis vitae eleifend quis, pellentesque at augue.</p>
            <img src={forest1} alt={"Forest"}/>
            <p className={globalStyle.textContent}>Pellentesque interdum metus mauris, id sagittis mi porttitor eu. Nullam aliquam quis libero sed maximus. Nunc dolor sem, sagittis quis aliquam quis, aliquet eget nulla. Donec bibendum leo sit amet gravida tincidunt. Nam eu ipsum orci. Nunc euismod auctor ex at euismod. Nam suscipit hendrerit ligula, eu sagittis libero vehicula egestas. Aliquam eget volutpat neque. Vestibulum quis leo nec nibh tempor pellentesque eget at tortor. Curabitur sed ultricies arcu, nec bibendum felis. Curabitur eleifend elit sed purus sagittis sagittis. Cras lobortis purus nisi, eu auctor odio faucibus eu. Nam auctor bibendum justo, at tempus lectus elementum aliquet.</p>
            <p className={globalStyle.textContent}>Vivamus molestie, ligula non aliquet ultricies, odio neque tempus est, in fermentum neque ipsum quis lorem. Donec consequat mi eget metus sodales, non pretium quam gravida. Aenean quis tempus risus. Aliquam massa odio, egestas vitae efficitur ac, tincidunt id sem. Etiam vel finibus magna. Quisque eleifend enim sed tincidunt sollicitudin. Aenean sed nulla sem. Quisque feugiat ipsum id nisi auctor, eget imperdiet justo tincidunt. Maecenas diam felis, hendrerit ac turpis nec, pellentesque pretium enim. Proin consequat ultricies nisi, ac convallis ante fermentum eget. Cras rhoncus vel dui in consequat. Suspendisse ac sem vitae velit pulvinar ultricies sit amet semper diam. Nunc pharetra mi id lobortis efficitur. Nam dignissim vulputate lectus, quis blandit sem posuere vitae. Sed neque urna, luctus congue elementum eu, cursus nec ante.</p>
            <img src={mountains1} alt={"Mountains"}/>
            <h3>Etiam massa ante</h3>
            <p className={globalStyle.textContent}>Etiam massa ante, maximus ut augue eget, molestie ullamcorper nunc. Aliquam nisi arcu, auctor et velit a, faucibus eleifend erat. Suspendisse consequat hendrerit aliquet. Mauris ut libero justo. Suspendisse vel porttitor lacus, quis semper nisl. Sed congue diam felis, rhoncus aliquam mauris consequat nec. Maecenas vehicula faucibus leo, nec tristique justo porttitor at. Donec nec vestibulum nisi. Duis tristique mi quis vestibulum sagittis.</p>
            <p className={globalStyle.textContent}>Maecenas nec quam pulvinar, congue risus nec, venenatis augue. Cras a odio neque. Nulla eget orci aliquet, ullamcorper orci eu, imperdiet sem. Pellentesque ipsum sem, mollis sed nibh at, cursus placerat elit. Aliquam quis laoreet lorem. Donec euismod tellus vel pretium mollis. Cras sit amet aliquet nisi, pellentesque pretium libero. In sit amet leo sollicitudin, gravida nisi sit amet, tincidunt turpis. Phasellus tellus risus, pretium vitae rhoncus nec, pulvinar eu purus.</p>
            <p className={globalStyle.textContent}>Vivamus egestas metus vitae sodales vulputate. Cras ornare neque facilisis placerat porttitor. Mauris in nisi in metus lacinia interdum. Duis et cursus velit. Aliquam fringilla non tellus sed pharetra. Suspendisse eu massa blandit, vulputate lectus in, mollis nulla. Nam congue finibus ante, sit amet scelerisque nunc suscipit id. Cras leo sapien, suscipit ac risus a, cursus lobortis nunc. Nullam pulvinar leo risus, eu iaculis nisl rhoncus eget. Mauris hendrerit sem mi, in condimentum risus tincidunt non. Curabitur facilisis vel leo tempus facilisis. Curabitur sed efficitur leo. Phasellus ac orci sit amet magna porttitor gravida eleifend sed lectus. Nunc ullamcorper, diam dapibus sollicitudin venenatis, elit nulla finibus felis, ut dictum dui quam sed ipsum.</p>
        </div> 
    )
}

export default ContentPage;